<?='<?xml version="1.0" encoding="UTF-8"?>'.PHP_EOL ?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    @isset($posts)
    <sitemap>
        <loc>{{route('home.post-sitemap')}}</loc>
        <lastmod>{{$posts->updated_at->tz('UTC')->toAtomString()}}</lastmod>
    </sitemap>
    @endisset
    @isset($categories)
    <sitemap>
        <loc>{{route('home.category-sitemap')}}</loc>
        <lastmod>{{$categories->updated_at->tz('UTC')->toAtomString()}}</lastmod>
    </sitemap>
    @endisset
    @isset($page)
    <sitemap>
        <loc>{{route('home.page-sitemap')}}</loc>
        <lastmod>{{$page->updated_at->tz('UTC')->toAtomString()}}</lastmod>
    </sitemap>
    @endisset
    @isset($blog)
    <sitemap>
        <loc>{{route('home.blog-sitemap')}}</loc>
        <lastmod>{{$blog->updated_at->tz('UTC')->toAtomString()}}</lastmod>
    </sitemap>
    @endisset
    @isset($Cblog)
    <sitemap>
        <loc>{{route('home.C-blog-sitemap')}}</loc>
        <lastmod>{{$Cblog->updated_at->tz('UTC')->toAtomString()}}</lastmod>
    </sitemap>
    @endisset
    @isset($Tblog)
    <sitemap>
        <loc>{{route('home.T-blog-sitemap')}}</loc>
        <lastmod>{{$Tblog->updated_at->tz('UTC')->toAtomString()}}</lastmod>
    </sitemap>
    @endisset
    @isset($products)
    <sitemap>
        <loc>{{route('home.product-sitemap')}}</loc>
        <lastmod>{{$products->updated_at->tz('UTC')->toAtomString()}}</lastmod>
    </sitemap>
    @endisset
    @isset($posts)
    <sitemap>
        <loc>{{route('home.images-sitemap')}}</loc>
        @isset($posts->updated_at)
            <lastmod>{{$posts->updated_at->tz('UTC')->toAtomString()}}</lastmod>
        @endisset
    </sitemap>
    @endisset
</sitemapindex>
